### ISSUE TITLE
Incomplete OpenAI Terms of Service

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/GenAI-declarations#120]
We actually track incomplete OpenAI [Terms of Service](https://openai.com/policies/terms-of-use) because there are [additional terms](https://openai.com/policies/service-terms) that govern your use of specific services.

That should be done by using [multiple source documents](https://docs.opentermsarchive.org/contributing-terms/#terms-with-multiple-source-documents).

**Comment by PierreMesure** [comment]
A lot of the interesting commitments regarding the Enterprise plans is not contained in the page called [Business terms](https://openai.com/policies/business-terms) but in another page referred in the terms: [Enterprise privacy](https://openai.com/enterprise-privacy).

**Comment by mvidonne** [comment]
@clementbiron  According to https://theintercept.com/2024/01/12/open-ai-military-ban-chatgpt/, OpenAI has just changed its usage policies. "The new policy retains an injunction not to “use our service to harm yourself or others” and gives “develop or use weapons” as an example, but the blanket ban on “military and warfare” use has vanished." Could you please add the usage policies  https://openai.com/policies/usage-policies 
Merci

**Comment by MattiSG** [comment]
> Could you please add the usage policies

This is already [tracked](https://github.com/OpenTermsArchive/GenAI-declarations/blob/main/declarations/OpenAI.json#L40-L50) as Acceptable Use Policy 🙂 

> A lot of the interesting commitments regarding the Enterprise plans are not contained in the page called [Business terms](https://openai.com/policies/business-terms) but in another page referred in the terms: [Enterprise privacy](https://openai.com/enterprise-privacy).

Thanks for pointing that out @PierreMesure! This could be tracked as [Business Privacy Policy](https://github.com/OpenTermsArchive/terms-types/blob/main/termsTypes.json#L257C4-L265) 🙂 please feel encouraged to add these terms!
