### ISSUE TITLE
Add Mistral APIs?

### ISSUE THREAD

**Issue by PierreMesure** [OpenTermsArchive/GenAI-declarations#122]
Mistral AI now has APIs and they come with [terms and conditions](https://mistral.ai/terms-of-service/). It would be great to add them to this collection.

**Comment by clementbiron** [comment]
Thanks, that's a good suggestion :)

From what we understand with @Ndpnt, Mistral AI publish a [Terms of Service](https://mistral.ai/terms-of-service/) for using its API which should be typed as a [Developer Terms](https://github.com/OpenTermsArchive/terms-types/blob/main/termsTypes.json#L30) and the [Terms of Service](https://mistral.ai/terms-of-use/) are called Terms of Use, it's a little bit confusing :)

We may also follow the [Privacy Policy](https://mistral.ai/privacy-policy/) and [Data Processor Agreement](https://mistral.ai/data-processing-agreement/).

**Comment by clementbiron** [comment]
I'd like to repeat the invitation I made to you [here](https://github.com/OpenTermsArchive/GenAI-declarations/issues/121#issuecomment-1931638562 ) to add this terms tracking. Let me know what you think?

**Comment by PierreMesure** [comment]
Done as well. 😊
