### ISSUE TITLE
ChatGPT, DALL·E, and OpenAI's Terms of Use outside EU

### ISSUE THREAD

**Issue by mvidonne** [OpenTermsArchive/GenAI-declarations#221]
It could be interesting to add terms of Use appling to the use of ChatGPT, DALL·E, and OpenAI’s other services outside **European Economic Area, Switzerland, or the UK**
https://openai.com/policies/row-terms-of-use/
so that it can be compared with the one already monitored by the opentermsarchive and available to the EU.

**Comment by MattiSG** [comment]
That's true, it would be very interesting!
At this stage however, considering that the geographical location of the server impacts the ability to fetch terms from a specific jurisdiction, collections are scoped by jurisdiction. Tracking such terms should thus be done in a separate collection, not in this one.
