### ISSUE TITLE
Remove `GitHub`

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/GenAI-declarations#57]
In #47, the reviewer mistakenly edited the service name `GitHub Copilot` to `GitHub` and superseded #47 with #48. Following discussion, the service name was brought back to `GitHub Copilot` in #50. However, this was made by _adding_ `GitHub Copilot` instead of _editing_ the `GitHub` declaration’s service name, leading to a duplicate.

### Correction

This requires @OpenTermsArchive/core intervention. @OpenTermsArchive/community-managers, please do not handle and focus on reviews.

- [ ] Remove `GitHub` declaration
- [ ] Remove `GitHub` versions

### Future prevention

@OpenTermsArchive/community-managers: in case of suspicion on the service name, please do not override and proceed with merge, but start a discussion instead. Wait until you `Approve` a pull request before merging, and wait for reply if you `Request changes` 🙂

**Comment by Cli4d** [comment]
Thanks for this. I'll be sure to take that into account when reviewing
